### ISSUE TITLE
Dynamic source and destenation selection

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion-module-nevion-mrp#1]
The ability to select a destination, and then what source you want it to use. All as a dynamic setup that scales with the number of in/outs, a bit like in the BMD video hub module.

**Comment by RasmuslundPaulsen** [comment]
That's exactly what I miss. It could also be nice with “take” function. May be with the option of choosing whether or not to use “Take”

**Comment by McHauge** [comment]
Updated the module, and after updating the core, then it will be available from there.
